### PR TITLE
Rename DashExpenses to DashBudget

### PR DESCRIPTION
**Pull request by Abdulrahman295**

### CODE REVIEW

**Comment by Sean-RD-Higgins** [comment]
Looks good so far, just missing the one in Title of App.

**Review by Sean-RD-Higgins — CHANGES_REQUESTED** [review]
Looks good so far, just missing the one in Title of App.

**Review by Sean-RD-Higgins — APPROVED** [review]
Looks good!

**Review by Withriin — APPROVED** [review]
Looks good.

**Pull request merged**
